modLoader="javafml"
loaderVersion="[2,)"
license="MIT"

[[mods]]
modId="ars_affinity"
version="1.0.1"
displayName="Ars Affinity"
authors="zeroregard"
description='''
A mod focused on affinity systems for Ars Nouveau.
'''

[[mixins]]
config="ars_affinity.mixins.json"

[[dependencies.ars_affinity]]
    modId="neoforge"
    mandatory=true
    versionRange="[21.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ars_affinity]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ars_affinity]]
    modId="ars_nouveau"
    mandatory=true
    versionRange="[5.8.2,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.ars_affinity]]
    modId="ars_elemental"
    mandatory=true
    versionRange="[0.7.6,)"
    ordering="AFTER"
    side="BOTH" 